project:
  name: messaging

springdoc:
  swagger-ui:
    url: /open-api.yaml

spring:
  profiles:
    active: kafka
  kafka:
    bootstrap-servers: localhost:9092
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
