project:
  name: messaging

springdoc:
  swagger-ui:
    url: /open-api.yaml

spring:
  profiles:
    active: rabbit
  kafka:
    bootstrap-servers: localhost:9092
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
