openapi: 3.0.0
info:
  title: Messaging
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
    description: local
paths:
  /events:
    get:
      summary: Returns a list of events.
      tags:
        - GitHub
      responses:
        '200':
          description: A JSON array of user's public repositories
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Repo'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '406':
          $ref: '#/components/responses/NotAcceptable'
  /repos/private/{userName}:
    get:
      summary: Returns a list of user's private and public repositories.
      tags:
        - GitHub
      parameters:
        - in: path
          name: userName
          schema:
            type: string
          required: true
          description: GitHub user name
        - in: query
          name: access_token
          schema:
            type: string
          description: GitHub personal access tokens
      responses:
        '200':
          description: A JSON array of user's private and public repositories
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Repo'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '406':
          $ref: '#/components/responses/NotAcceptable'
components:
  schemas:
    Repo:
      type: object
      properties:
        name:
          type: string
        ownerLogin:
          type: string
        branches:
          type: array
          items:
            $ref: '#/components/schemas/Branch'
    Branch:
      type: object
      properties:
        name:
          type: string
        sha:
          type: string
    Error:
      type: object
      properties:
        status:
          type: number
        message:
          type: string
  responses:
    NotFound:
      description: Github user was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: User not authorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotAcceptable:
      description: Invalid media type was specified in the `Accept`header (value should be`Application/json`).
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
tags:
  - name: GitHub
    description: Wrapper api
